# -*- coding: utf-8 -*-
"""Cópia de continuarrrr

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PDOmGIxGCtrh7H4hGxXEDk2zBZGjFGQ-

1-Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

nota = int(input("digite um numero entre 0 a 10? "))

while (nota < 0) or (nota > 10):
  print("numero invalido")
  nota = int(input("digite um numero novamente entre 0 e 10 "))
  print("numero valido")

"""Faça um programa que calcule o mostre a média aritmética de N notas"""

usuario = float(input("quantas notas vao ser?: "))
soma = 0
contador = 0

while usuario > contador:
  notas_inseridas = float(input("digite as notas: "))
  contador = contador +1
  soma = soma + notas_inseridas
media = soma + usuario
print(f"a soma total e {soma} e a media aritimetica {soma/2}")

"""Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

nome_1 = input("insira seu seu nome?: ")
senha = input("insira sua senha: ")

while (nome_1) == (senha):
  print("Acesso invalido")
  nome_1 = input("insira seu nome?: ")
  senha = input("insira  sua senha: ")
else:
  print("acesso liberado")

"""Um funcionário de uma empresa recebe aumento salarial anualmente. Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
5000,00 ; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de 1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do percentual do ano anterior. Faça um programa que determine o salário atual desse funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o salário inicial do funcionário.
"""

ano = 1996
aumento = 0.015
salario = 1000

while ano < 2025:
  ano+=1
  salario += salario * aumento
  aumento *=2
  print(f"no {ano} seu salario era de {salario}")

"""Faça um programa que leia e valide as seguintes informações:  Nome: maior que 3 caracteres;  Idade: entre 0 e 150;  Salário: maior que zero;  Sexo: 'f' ou 'm';  Estado Civil: 's', 'c', 'v', 'd';"""

