# -*- coding: utf-8 -*-
"""WHILE EXER

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QUjeGrJZwQun3eOCItSracXYNXLHtcSV

1. Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem
caso o valor seja inválido e continue pedindo até que o usuário informe um valor
válido.
"""

usuario_1 = float(input("digite uma nota entre 0 e 10 "))

while (usuario_1<0 ) or (usuario_1>10):
  print("nota invalida")
  usuario_1 = float(input("digite uma nota entre 0 e 10 "))
  print("nota valida")

"""2. Faça um programa que calcule o mostre a média aritmética de N notas"""

nota_inserida = float(input("quantas notas vao ser "))
  soma = 0
  contador = 0
while contador < nota_inserida:
   nota_inserida = float(input("digite sua nota "))
   contador +=1
   soma += nota_inserida
   print(f"soma total {soma} e a media {soma/nota_inserida}")

"""3. Faça um programa que leia um nome de usuário e a sua senha e não aceite a
senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a
pedir as informações.

"""

nome = input("qual seu nome ? ")
senha = input("digite sua senha ")


while nome == senha:
  print("informacao invalida ")
  senha = input("digite uma senha ")
  print("informacao valida")

"""4. Um funcionário de uma empresa recebe aumento salarial anualmente.
Sabe-se que: Esse funcionário foi contratado em 1995, com salário inicial de R$
1.000,00; Em 1996 recebeu aumento de 1,5% sobre seu salário inicial; A partir de
1997 (inclusive), os aumentos salariais sempre correspondem ao dobro do
percentual do ano anterior. Faça um programa que determine o salário atual desse
funcionário. Após concluir isto, altere o programa permitindo que o usuário digite o
salário inicial do funcionário.
"""

# recebe aumento anualmente
# foi contratado em 1995
# salario inicial de 1.000
# em 1996 recebeu 1,5%
# 97 inclusive dobro do ano anterior %

aumento = 0.015
salario_inicial = 1000
ano = 1995

while ano < 2024:
  ano += 1
  salario_inicial += salario_inicial * aumento
  aumento *= 2
  print(f"Salario atual em {ano} = {salario_inicial}")

"""5. Faça um programa que leia e valide as seguintes informações:
 Nome: maior que 3 caracteres;
 Idade: entre 0 e 150;
 Salário: maior que zero;
 Sexo: 'f' ou 'm';
 Estado Civil: 's', 'c', 'v', 'd';

"""

nome = str(input("digite seu nome "))

while len(nome)<=3:
  nome = str(input("nome invalido digite novamente "))

idade = int(input("digite sua idade "))

while idade <0 or idade >150:
  idade = int(input("digite sua idade novamente "))

salario = float(input("digite seu salario "))

while salario <0:
  salario = float(input("digite seu salario novamente "))

sexo = str(input("digite seu sexo entre f ou m"))

while sexo != "f"  or sexo != "m":
 sexo = str(input("digite seu sexo novamente "))


estado_civil = str(input("digite seu estado civil "))

while estado_civil != "s" and estado_civil != "c" and estado_civil != "v" and estado_civil != "d":
  estado_civil = str(input("digite seu estado civil novamente "))

"""6. Supondo que a população de um país A seja da ordem de 80000 habitantes com
uma taxa anual de crescimento de 3% e que a população de B seja 200000
habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e
escreva o número de anos necessários para que a população do país A ultrapasse
ou iguale a população do país B, mantidas as taxas de crescimento.
"""

pais_A = 80000
aumentoA = 0.03
pais_B = 200000
aumentoB = 0.015
ano = 2024

while pais_B > pais_A:
  pais_A += pais_A * aumentoA
  pais_B += pais_B * aumentoB
  ano +=1
  print(f"no ano {ano} o pais A tinha {pais_A} e o pais B tinha {pais_B}")

"""7. Faça um programa que calcule o fatorial de um número inteiro fornecido pelo
usuário. Ex.: 5!=5.4.3.2.1=120
"""

numero_inteiro = int(input("digite um numero inteiro "))
resultado = 1
while numero_inteiro != 0:
  resultado *=  numero_inteiro
  numero_inteiro -=1
  print(f"{resultado}")

 #hhhh

"""8. Faça um programa que solicite ao usuário números indefinidamente até que ele
digite 0. Em seguida, o programa deve imprimir a média dos números digitados.
"""

usuario_1 = float(input("digite numeros indefinidos "))
soma = 0
contador = 0
media = 0
condicao = 1

while condicao != 0:
  usuario_1 = float(input("digite numeros indefinidos "))
  usuario_1 += usuario_1 + soma/2
  contador += usua